package pe.gob.osce.redcompradores.enums;

public enum ParametroClaveEnum {
	MAX_SIZE_VIDEO, 
	MAX_SIZE_IMAGE, 
	MAX_SIZE_FILE, 
	TYPE_VIDEO, 
	TYPE_IMAGE, 
	TYPE_FILE,
	VALID_RENIEC,
	VALID_SEACE,
	TENOR_REGISTRO_NUEVO,
	TENOR_AMONESTACION_BAJA,
	TENOR_RESET_PASSWORD,
	TENOR_NOTIFICACION_COMENTARIO,
	TENOR_NOTIFICACION_MEJORA,
	LIMIT_MESSAGE_CHATROOM,
	LIMIT_MESSAGE_PUBLICACION,
	LIMIT_PALABRA_CLAVE,
	SEND_MAIL_MEJORA,
	LINK_RED_COMPRADORES
}
